export const enum RoutesName {
  Home,
  Examples,
  ExamplesCubicBezier,
  ExamplesDynamicTweenFollow,
  ExamplesChainTween,
  ExamplesSmoothPath,
  Docs,
  DocsInstallation,
  DocsDynamicTween,
  DocsSimpleTween,
  DocsTween,
  DocsTimelineTween,
  DocsCubicBezier,
  DocsEquations,
  DocsSmoothPath,
  NotFound,
}
