export const enum RoutesName {
  Home,
  Examples,
  ExamplesCubicBezier,
  ExamplesDynamicTweenFollow,
  ExamplesChainTween,
  ExamplesSmoothPath,
  Docs,
  DocsInstallation,
  DocsDynamicTween,
  DocsTween,
  DocsChainTween,
  DocsCubicBezier,
  DocsEquations,
}
